[book]
title = "FBC Press: Tailwind CSS ― 仕組みと思想から理解する"
authors = ["FjordBootCamp"]
language = "ja"
multilingual = false
src = "manuscript"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/fjordllc/tailwind-css-textbook-ja"
edit-url-template = "https://github.com/fjordllc/tailwind-css-textbook-ja/edit/main/{path}"
additional-css = ["theme/tailwind-css-textbook.css"]
additional-js = ["theme/textbook-footer.js"]
no-section-label = true

[output.html.search]
enable = true
use-boolean-and = true

[output.html.fold]
enable = true
level = 1
